$ define/key/terminate 1 "SW"
$ define/key/terminate 2 "S"
$ define/key/terminate 3 "SE"
$ define/key/terminate 4 "W"
$ define/key/terminate 5 "LOOK"
$ define/key/terminate 6 "E"
$ define/key/terminate 7 "NW"
$ define/key/terminate 8 "N"
$ define/key/terminate 9 "NE"
$ define/key/terminate PF1 "OPEN DOOR"
$ define/key/terminate PF2 "INVENTORY"
$ define/key/terminate PF3 "SCORE"
$ define/key/terminate PF4 "QUIT"

