[inherit('lib$:typedef')] module dscdef;

const	dsc$k_dtype_z = 0;
	dsc$k_dtype_v = 1;
	dsc$k_dtype_bu = 2;
	dsc$k_dtype_wu = 3;
	dsc$k_dtype_lu = 4;
	dsc$k_dtype_qu = 5;
	dsc$k_dtype_ou = 25;
	dsc$k_dtype_b = 6;
	dsc$k_dtype_w = 7;
	dsc$k_dtype_l = 8;
	dsc$k_dtype_q = 9;
	dsc$k_dtype_o = 26;
	dsc$k_dtype_f = 10;
	dsc$k_dtype_d = 11;
	dsc$k_dtype_g = 27;
	dsc$k_dtype_h = 28;
	dsc$k_dtype_fc = 12;
	dsc$k_dtype_dc = 13;
	dsc$k_dtype_gc = 29;
	dsc$k_dtype_hc = 30;
	dsc$k_dtype_cit = 31;
	dsc$k_dtype_vu = 34;
	dsc$k_dtype_t = 14;
	dsc$k_dtype_vt = 37;
	dsc$k_dtype_nu = 15;
	dsc$k_dtype_nl = 16;
	dsc$k_dtype_nlo = 17;
	dsc$k_dtype_nr = 18;
	dsc$k_dtype_nro = 19;
	dsc$k_dtype_nz = 20;
	dsc$k_dtype_p = 21;
	dsc$k_dtype_zi = 22;
	dsc$k_dtype_zem = 23;
	dsc$k_dtype_dsc = 24;
	dsc$k_dtype_bpv = 32;
	dsc$k_dtype_blv = 33;
	dsc$k_dtype_adt = 35;
	dsc$k_dtype_cad = 178;
	dsc$k_dtype_ent = 179;
	dsc$k_dtype_gbl = 180;
	dsc$k_dtype_ept = 181;
	dsc$k_dtype_r11 = 182;
	dsc$k_dtype_fld = 183;
	dsc$k_dtype_pct = 184;
	dsc$k_dtype_dpc = 185;
	dsc$k_dtype_lbl = 186;
	dsc$k_dtype_slb = 187;
	dsc$k_dtype_mod = 188;
	dsc$k_dtype_eom = 189;
	dsc$k_dtype_rtn = 190;
	dsc$k_dtype_eor = 191;

	dsc$k_class_z = 0;
	dsc$k_class_s = 1;
	dsc$k_class_d = 2;
	dsc$k_class_v = 3;
	dsc$k_class_a = 4;
	dsc$k_class_p = 5;
	dsc$k_class_pi = 6;
	dsc$k_class_j = 7;
	dsc$k_class_ji = 8;
	dsc$k_class_sd = 9;
	dsc$k_class_nca = 10;
	dsc$k_class_vs = 11;
	dsc$k_class_vsa = 12;
	dsc$k_class_ubs = 13;
	dsc$k_class_uba = 14;
	dsc$k_class_sb = 15;
	dsc$k_class_ubsb = 16;
	dsc$k_class_bfa = 191;

type	$descriptor = [quad] record
			dsc$w_length : $uword;
			dsc$b_dtype : $ubyte;
			dsc$b_class : $ubyte;
			dsc$a_pointer : unsigned;
		      end;

end.
